platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest
inputs:
  - name: gpupgrade_src
  - name: sqldump
  - name: cluster_env_files
run:
  path: gpupgrade_src/ci/scripts/load-dump.sh
params:
  OLD_PACKAGE:
